# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-05 10:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20180605_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_image',
            field=models.ImageField(default='Image', upload_to='articles/'),
        ),
        migrations.AlterField(
            model_name='editor',
            name='first_name',
            field=models.CharField(max_length=60),
        ),
    ]
